config/routes.rb
TimeTracker::Application.routes.draw do
  resources :timesheets do
    resources :days
  end

end

app/models/day.rb
class Day < ActiveRecord::Base
  belongs_to :timesheet
  validates_presence_of :arrival, :departure
  validates_presence_of :lunchtime, :if => "!back_from_lunch.nil?"
  validates_presence_of :back_from_lunch, :if => "!lunchtime.nil?"

  validate :uniqueness_of_date, :departure_cannot_be_earlier_than_arrival

  def uniqueness_of_date
    if arrival and departure
      date = arrival.to_s.split(" ")[0]
      unless (Day.where(:arrival => "#{date} 00:00".."#{date} 23:59")).empty?
        errors.add(:arrival, "date must be unique")
      end
    end
  end

  def departure_cannot_be_earlier_than_arrival
    if arrival and departure and departure < arrival
      errors.add(:arrival, "must be earlier than departure")
    end
  end

  def total_worked_time
    @total_time = departure - arrival if departure and arrival
    @total_time = @total_time - lunch_time
    @total_time = @total_time - other.hour*3600 - other.min*60 - other.sec if other

    #total_worked_time = fill_with_zero(hours) + ":" + fill_with_zero(mins) + ":" + fill_with_zero(secs)
    total_worked_time = "#{hours(@total_time)}:#{mins(@total_time)}:#{secs(@total_time)}"
  end

  def hours(time)
    fill_with_zero((time/3600).floor)
  end

  def mins(time)
    fill_with_zero(((time%3600)/60).floor)
  end

  def secs(time)
    fill_with_zero(((time%3600)%60).floor)
  end

  def lunch_time
    if lunchtime && back_from_lunch
      return back_from_lunch - lunchtime
    else
      return 0
    end
  end

  def formated_lunch_time
    time = lunch_time
    "#{hours(time)}:#{mins(time)}:#{secs(time)}"
  end

  def fill_with_zero(number)
    if number > 9
      number.to_s
    else
      "0"+number.to_s
    end
  end
end

app/models/timesheet.rb
class Timesheet < ActiveRecord::Base
  validates_presence_of :owner
  validates_uniqueness_of :owner
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.all
  end

  def new
    @day = Day.new
  end

  def create
    @day = Day.new(params[:day])

    if @day.save
      redirect_to :action => :index
    else
      redirect_to :action => :new
    end
  end

  def show
    @day = Day.find(params[:id])
  end
end

app/controllers/timesheets_controller.rb
class TimesheetsController < ApplicationController
  def new
    @timesheet = Timesheet.new
  end

  def show
    @timesheet = Timesheet.find(params[:id])
    redirect_to "/timesheets/#{@timesheet.id}/days"
  end

  def index
    @timesheets = Timesheet.all
  end

  def create
    @timesheet = Timesheet.new(params[:timesheet])

    if @timesheet.save
      redirect_to "/timesheets/#{@timesheet.id}/days"
    else
      redirect_to :action => "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/timesheets_helper.rb
module TimesheetsHelper
end

app/views/days/index.html.erb
<table>
  <tr>
    <th>Arrival</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

<% unless @days.empty? %>
  <% @days.each do |day| %>
    <tr>
      <td><%=h day.arrival.to_s.split(" ")[0] %></td>
      <td><%= link_to 'Show', "/timesheets/#{params[:timesheet_id]}/days/#{day.id}", :id => "show_#{day.arrival.to_s.split(" ")[0]}" %></td>
    </tr>
  <% end %>
<% else %>
  <p>No days available.</p>
<% end %>
</table>

<%= link_to "New day", new_timesheet_day_path %>

app/views/days/new.html.erb
<h1>Start new day</h1>

<%= form_for [@timesheet, @day], :url => timesheet_days_path do |form| %>
    <%= form.label :arrival %>
    <%= form.text_field :arrival %>
    <%= form.label :departure %>
    <%= form.text_field :departure %>
    <%= form.label :lunchtime %>
    <%= form.text_field :lunchtime %>
    <%= form.label :back_from_lunch %>
    <%= form.text_field :back_from_lunch %>
    <%= form.submit "Save" %>
<% end %>

app/views/days/show.html.erb
<table>
  <tr>
    <th>Arrival</th>
    <th>Departure</th>
    <th>Total worked time</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <tr>
    <td id="arrival"><%=h @day.arrival %></td>
    <td><%=h @day.departure %></td>
    <td><%=h @day.total_worked_time %></td>
  </tr>
</table>

<%= link_to "New day", new_timesheet_day_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title || 'Time Tracker' %></title>
  <%= stylesheet_link_tag 'css/application.css' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<% if flash[:notice] or flash[:error] %>
	<div id="message-box">
		<p class="notice"><%= flash[:notice] %></p>
		<p class="error"><%= flash[:error] %></p>

		<div class="background"></div>
	</div>
<% end %>

<div id="glb-doc">
  <div id="glb-cabecalho">
    <div class="conteudo-cabecalho">
		  <div class="header-topo">
		    <span class="sistema">Time Tracker</span>
		  </div>

	    <div class="header-base">
				<%= link_to raw("#{ image_tag('spacer.gif')} Home"), timesheets_path, :class => 'home' %>
	    </div>
		</div>		
  </div>

  <div id="glb-corpo">
    <div class="glb-bloco">
      <div class="glb-grid-12">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/timesheets/index.html.erb
<table>
  <tr>
    <th>Timesheets</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

<% unless @timesheets.empty? %>
  <% @timesheets.each do |timesheet| %>
    <tr>
      <td><%=h timesheet.owner %></td>
      <td><%= link_to 'Show', timesheet, :id => "show_#{timesheet.owner}" %></td>
      <td><%= link_to 'Edit', edit_timesheet_path(timesheet) %></td>
      <td><%= link_to 'Delete', timesheet, :confirm => 'Are you sure?', :method => :delete, :id => "delete_#{timesheet.owner}" %></td>
    </tr>
  <% end %>
<% else %>
  <p>No timesheets available.</p>
<% end %>
</table>

<%= link_to "New timesheet", new_timesheet_path %>

app/views/timesheets/new.html.erb
<h1>Create new timesheet</h1>

<%= form_for(@timesheet) do |form| %>
    <%= form.label :owner, raw('Your name:') %>
    <%= form.text_field :owner %>
    <%= form.submit "Create" %>
<% end %>